### ISSUE TITLE
does NOT HANDLE TAIL CALL PROPERLY !!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by meepdarknessmeep** [FPtje/FProfiler#1]
pls fix

debug.sethook throws event tail call after calling
```lua
(function() return (function() end)() end)()
```

**Comment by meepdarknessmeep** [comment]
that's not fixed, trust me im a doctor

anyways tail call is, internally, like this:

```lua
local function memes()
    return print "hi"
end

memes()
```

this translates to roughly:

```
push outterfunction
goto outterfunction
push memes
goto memes
pop r0    ; memes
push print
goto print
; print is called til return
pop r0 ;outterfunction
goto outterfunction
pop r0 ; nothing left
```

**Comment by FPtje** [comment]
Surely when the text says "tail call", I'm dealing with a tail call. You're not describing a problem with my profiler, you're describing tail calls.

What am I doing wrong and what would you suggest me to do to fix it?

**Comment by meepdarknessmeep** [comment]
you are not changing the stack to work how it does it

**Comment by FPtje** [comment]
What stack? I keep track of several things, I call none of them stack.

**Comment by meepdarknessmeep** [comment]
idk im gay

**Comment by FPtje** [comment]
that's great
