### ISSUE TITLE
Serverside profiling doesn't print anything

### ISSUE THREAD

**Issue by Jabbers99** [FPtje/FProfiler#14]
![image](https://user-images.githubusercontent.com/39739543/109178823-2a5a9c80-7781-11eb-9a09-e441ce47e587.png)
I have the correct perms, nothing is listed

**Comment by FPtje** [comment]
![hl2_2021-02-27_16-49-19](https://user-images.githubusercontent.com/1202014/109392335-c7513d00-791b-11eb-962e-54df7c920847.png)

Cannot reproduce locally, look for errors, both clientside and serverside

**Comment by Jabbers99** [comment]
I've reininstalled several times, no errors clientside or serverside and I've double checked I definitely have the correct permissions

**Comment by FPtje** [comment]
I think that for some reason you're not getting the data, or FProfiler is not being run properly on the server.

Note: it is possible to install FProfiler on the client, but not the server. That would probably cause the symptoms you see. Make sure FProfiler is on the server.

**Comment by Jabbers99** [comment]
Yeah FProfiler is definitely on the server...

**Comment by FPtje** [comment]
I'm afraid the only way to find the cause then is to add debug print statements to the FProfiler code, see if the command is executed, see if the net messages with data are being sent and that sort of stuff.
