### ISSUE TITLE
Upvalues getting called yet seemingly not getting used?

### ISSUE THREAD

**Issue by wrefgtzweve** [FPtje/FProfiler#17]
https://github.com/FPtje/FProfiler/blob/160ce85640f61d5c4f741f1ca5c1e74e517c02d4/lua/fprofiler/gather.lua#L5
This function is getting called whenever any function returns in lua, yet i don't see `upvalues` being used anywhere. I might be missing something but it feels like this is running for no reason.

Same for
<https://github.com/FPtje/FProfiler/blob/160ce85640f61d5c4f741f1ca5c1e74e517c02d4/lua/fprofiler/gather.lua#L19>
Im likely missing something

Fprofiler seems to work fine without them

**Comment by FPtje** [comment]
Thanks for reporting. I'll take a look when I have time 👍

**Comment by FPtje** [comment]
Looks like you're right. Thanks!
