### ISSUE TITLE
Doesn't log server side

### ISSUE THREAD

**Issue by Ilunga1** [FPtje/FProfiler#6]
Put this into my servers addons. However, it doesn't log server side.

I made sure I was in the superadmin group. I looked this up and couldn't find a solution, but one guy said the same thing 3 weeks ago.

**Comment by FPtje** [comment]
Well what happens when you try?

**Comment by Ilunga1** [comment]
Nothing pops up. Nothing at all. I have quite a serious lag issue at 20 plus players so this would be helpful.

Only clienside works

**Comment by Ilunga1** [comment]
Tried reinstalling it pal, still the same.

**Comment by Ilunga1** [comment]
bump - super important I get this to work

**Comment by FPtje** [comment]
I don't know what's going on. It works for me.

**Comment by Ilunga1** [comment]
Could you try look into it? There is obviously a reason.

**Comment by Ilunga1** [comment]
I'd be super grateful man, I'm having random crashes on the server. Used to be big lag spikes, we fixed that now we're having random straight up crashes.

**Comment by FPtje** [comment]
This doesn't solve crashes in the first place. Also, since I can't reproduce it myself, I can't debug it. I have no time to look at someone else's server. You may have an addon that messes with the debug functions. Maybe the addon isn't properly installed serverside. Check your server log for errors.

**Comment by Ilunga1** [comment]
I know it doesn't solve crashes. I didn't say it did. I'd be using it to help me find out the sources of lag.
Thanks for reply

**Comment by FPtje** [comment]
I'm sorry, I can't help you.

**Comment by Ilunga1** [comment]
Would this have anything to do with it? 
TCBDealer.settings.debug = false

**Comment by FPtje** [comment]
I don't think so
